[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-ml-learning-plan"
version = "0.1.0"
description = "Agentic AI + Recommenders Learning Journey (52 weeks)"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
